/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ctt.back.end;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SurveyApplication 
{
	public static void main(String[] args) 
	{
    	SpringApplication.run(SurveyApplication.class, args);
    }
}
